DROP TABLE IF EXISTS signup_requests;
DROP TABLE IF EXISTS checks;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS incident_notifications;
DROP TABLE IF EXISTS incidents;
DROP TABLE IF EXISTS probes;
DROP TABLE IF EXISTS check_results;
